# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Python tests

on: [workflow_call]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/workflows/install-python-and-poetry.yml
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: poetry install --no-root

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run ruff . --select=E9,F63,F7,F82 --show-source
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run ruff . --exit-zero --select=C901 --line-length=127 --statistics

    - name: Test with pytest
      run: |
        poetry run pytest
