name: Test and publish the repo to PyPI on release

on:
  release:
    types: [released]

jobs:
  run_tests:
    uses: ./.github/workflows/run-tests.yml
  publish:
    uses: ./.github/workflows/publish-with-poetry.yml
    needs: [run_tests]
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
